package com.ourteam.pcd.persistance;
// Generated Mar 3, 2018 1:32:26 PM by Hibernate Tools 5.2.6.Final

/**
 * Classe generated by hbm2java
 */
public class Classe implements java.io.Serializable {

	private String nom;

	public Classe() {
	}

	public Classe(String nom) {
		this.nom = nom;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
