package com.ourteam.pcd.persistance;
// Generated Mar 3, 2018 1:32:26 PM by Hibernate Tools 5.2.6.Final

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	private String email;
	private String password;

	public Compte() {
	}

	public Compte(String email) {
		this.email = email;
	}

	public Compte(String email, String password) {
		this.email = email;
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
