package com.ourteam.pcd.persistance;
// Generated Mar 3, 2018 1:32:26 PM by Hibernate Tools 5.2.6.Final

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant implements java.io.Serializable {

	private String numinscription;
	private String nom;
	private String prenom;
	private String telephone;
	private String email;

	public Etudiant() {
	}

	public Etudiant(String numinscription, String nom, String prenom, String telephone, String email) {
		this.numinscription = numinscription;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.email = email;
	}

	public String getNuminscription() {
		return this.numinscription;
	}

	public void setNuminscription(String numinscription) {
		this.numinscription = numinscription;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
