package com.ourteam.pcd.persistance;
// Generated Mar 3, 2018 1:32:26 PM by Hibernate Tools 5.2.6.Final

/**
 * ResponsableScolarite generated by hbm2java
 */
public class ResponsableScolarite implements java.io.Serializable {

	private String idResponsable;
	private String nom;
	private String prenom;
	private String telephone;
	private String email;

	public ResponsableScolarite() {
	}

	public ResponsableScolarite(String idResponsable, String nom, String prenom, String telephone, String email) {
		this.idResponsable = idResponsable;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.email = email;
	}

	public String getIdResponsable() {
		return this.idResponsable;
	}

	public void setIdResponsable(String idResponsable) {
		this.idResponsable = idResponsable;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
